# mange dependencies with brew https://brew.sh/

brew "docker"
brew "docker-compose"
brew "colima"         # Container runtimes on MacOS (and Linux) with minimal setup
brew "tmux"           # Terminal multiplexer
